<script lang="ts">
    import Header from './header.svelte'
    import Footer from './footer.svelte'
</script>

<svelte:head>
  <title>Privacy Policy | {__APP_TITLE__}</title>
</svelte:head> 

<section class="bg-local bg-cover" >
    <Header transparent light main/>
</section>

<div class="antialiased  bg-white w-full ">
    <div class="flex justify-center">
        <article class="   w-full prose prose-base prose-zinc mx-2">
            <h1>Privacy Policy</h1>
            <p>Effective date: February 01, 2025</p>                        
            <p>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
            <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our <a href="/terms-and-conditions">Terms and Conditions</a>.</p>

            <h2>Definitions</h2>
            <ul>
                <li><h3>Human Dialog</h3>
                    <p>"Human Dialog" refers to Human Dialog S.A. company located at Kazimierza Wielkiego 27, 50-077 Wrocław, Poland. <br/>When “We” or “Us” or “Our” are used in this policy, it is a reference to Human Dialog.</p>
                </li>
                <li><h3>Service</h3>
                    <p>Service means the <a href="https://octopus.objectreef.dev">https://octopus.objectreef.dev</a> website operated by Human Dialog.</p>
                </li>

                <li><h3>Personal Data</h3>
                    <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                </li>

                <li><h3>Usage Data</h3>
                    <p>Usage Data is data collected automatically either generated by the use of the Service, from the Service infrastructure itself (for example, the duration of a page visit) or running Service.</p>
                </li>

                <li><h3>Cookies</h3>
                    <p>Cookies are small files stored on your device (computer or mobile device).</p>
                </li>

                <li><h3>Data Controller</h3>
                    <p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
                    <p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
                </li>

                <li><h3>Data Processors (or Service Providers)</h3>
                    <p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>
                    <p>We may use the services of various Service Providers in order to process your data more effectively.</p>
                </li>

                <li><h3>Data Subject (or User)</h3>
                    <p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
                </li>
            </ul>

            <h2>Information Collection and Use</h2>
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
            <h3>Types of Data Collected</h3>
            <h4>Personal Data</h4>
            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
                <ul>
                    <li>Email address</li>
                    <li>Name</li>
                    <li>Cookies and Usage Data</li>
                </ul>
            <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</p>
            <h4>Usage Data</h4>
            <p>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").</p>
            <p>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>
            <p>We may also collect usage data through the Service, as data sent from time to time in the background of process operation. Telemetry data is collected to help understand how to improve the product.  For example, this data helps in debugging problems, such as slow Service startup, and in prioritizing new features. </p>
            <p>The Service collects three basic types of telemetry data:</p>
            <ul>
                <li>Crash reports - collect diagnostic information when ObjectReef crashes and send it to Human Dialog to help understand why the crash occurred and what changes are needed to prevent future failures. </li>
                <li>Error telemetry - collects information about errors that do not cause the Service to crash but are unexpected.</li>
                <li>Features usage data - collects information about how features are used and work in ObjectReef, which helps us prioritize future product improvements.</li>
            </ul>

            <h4>Tracking & Cookies Data</h4>
            <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
            <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>
            <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
            <p>Examples of Cookies we use:</p>
            <ul>
                <li>Session Cookies. We use Session Cookies to operate our Service.</li>
                <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
                <li>Security Cookies. We use Security Cookies for security purposes.</li>
                <li>Advertising Cookies. Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
            </ul>

            <h2>Use of Data</h2>
            <p>Human Dialog uses the collected data for various purposes:</p>
            <ul>
                <li>To provide and maintain our Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide customer support</li>
                <li>To gather analysis or valuable information so that we can improve our Service</li>
                <li>To monitor the usage of our Service</li>
                <li>To detect, prevent and address technical issues</li>
                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
            </ul>

            <h2 class="text-left">Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</h2>
            <p>If you are from the European Economic Area (EEA), Human Dialog legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
            <p>Human Dialog may process your Personal Data because:</p>
            <ul>
                <li>We need to perform a contract with you</li>
                <li>You have given us permission to do so</li>
                <li>The processing is in our legitimate interests and it is not overridden by your rights</li>
                <li>For payment processing purposes</li>
                <li>To comply with the law</li>
            </ul>
            
            <h2>Retention of Data</h2>
            <p>Human Dialog will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.</p>
            <p>Human Dialog will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>

            <h2>Transfer of Data</h2>
            <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
            <p>If you are located outside European Economic Area (EEA) and choose to provide information to us, please note that we transfer the data, including Personal Data, to European Economic Area (EEA) and process it there.</p>
            <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p>Human Dialog will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

            <h2>Disclosure of Data</h2>
            <h3>Business Transaction</h3>
            <p>If Human Dialog is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

            <h3>Disclosure for Law Enforcement</h3>
            <p>Under certain circumstances, Human Dialog may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

            <h3>Legal Requirements</h3>
            <p>Human Dialog may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul>
                <li>To comply with a legal obligation</li>
                <li>To protect and defend the rights or property of Human Dialog</li>
                <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>To protect the personal safety of users of the Service or the public</li>
                <li>To protect against legal liability</li>
            </ul>

            <h2>Security of Data</h2>
            <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

            <h2 class="text-left">Our Policy on "Do Not Track" Signals under the California Online Protection Act (CalOPPA)</h2>
            <p>We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
            <p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>

            <h2>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</h2>
            <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Human Dialog aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.</p>
            <p>If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
            <p>In certain circumstances, you have the following data protection rights:</p>
            <ul>
                <li>The right to access, update or delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</li>
                <li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
                <li>The right to object. You have the right to object to our processing of your Personal Data.</li>
                <li>The right of restriction. You have the right to request that we restrict the processing of your personal information.</li>
                <li>The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
                <li>The right to withdraw consent. You also have the right to withdraw your consent at any time where Appwrite relied on your consent to process your personal information.</li>
            </ul>

            <p>Please note that we may ask you to verify your identity before responding to such requests.</p>

            <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

            <h2>Service Providers</h2>
            <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
            <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

            <h3>Analytics</h3>
            <p>We may use third-party Service Providers to monitor and analyse the use of our Service.</p>
            <ul>
                <li><h4>Google Analytics</h4>
                    <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</p>
                    <p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a></p>
                </li>
            </ul>

            <h3>Behavioral Remarketing</h3>
            <p>Human Dialog uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>

            <ul>
                <li><h4>Google AdWords</h4>
                    <p>Google AdWords remarketing service is provided by Google Inc.</p>
                    <p>You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a></p>
                    <p>Google also recommends installing the Google Analytics Opt-out Browser Add-on - <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a> - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.</p>
                    <p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a></p>
                </li>

                <li><h4>X (Twitter)</h4>
                    <p>Twitter remarketing service is provided by X Inc.</p>
                    <p>You can opt-out from Twitter's interest-based ads by following their instructions: <a href="https://support.twitter.com/articles/20170405">https://support.twitter.com/articles/20170405</a></p>
                    <p class="text-left">You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: <a href="https://twitter.com/privacy">https://twitter.com/privacy</a></p>
                </li>

                <li><h4>Facebook</h4>
                    <p>Facebook remarketing service is provided by Facebook Inc.</p>
                    <p class="text-left">You can learn more about interest-based advertising from Facebook by visiting this page: <a href="https://www.facebook.com/help/516147308587266">https://www.facebook.com/help/516147308587266</a></p>
                    <p class="text-left">To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: <a href="https://www.facebook.com/help/568137493302217">https://www.facebook.com/help/568137493302217</a></p>
                    <p>Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA <a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>, the Digital Advertising Alliance of Canada in Canada <a href="http://youradchoices.ca/">http://youradchoices.ca/</a> or the European Interactive Digital Advertising Alliance in Europe <a href="http://www.youronlinechoices.eu/">http://www.youronlinechoices.eu/</a>, or opt-out using your mobile device settings.</p>
                    <p class="text-left">For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: <a href="https://www.facebook.com/privacy/explanation">https://www.facebook.com/privacy/explanation</a></p>
                </li>

                <li><h4>LinkedIn</h4>
                    <p>LinkedIn remarketing service is provided by LinkedIn Inc.</p>
                    <p>You can learn more about interest-based advertising from LinkedIn by visiting this page: <a href="https://www.linkedin.com/legal/ads-policy">https://www.linkedin.com/legal/ads-policy</a></p>
                    <p class="text-left">To opt-out from LinkedIn's interest-based ads, follow these instructions from LinkedIn: <a href="https://www.linkedin.com/help/linkedin/answer/62931/manage-advertising-preferences">https://www.linkedin.com/help/linkedin/answer/62931/manage-advertising-preferences</a></p>
                    <p class="text-left">For more information on the privacy practices of LinkedIn, please visit LinkedIn's Privacy Policy: <a href="https://www.linkedin.com/legal/privacy-policy">https://www.linkedin.com/legal/privacy-policy</a></p>
                </li>
            </ul>

            <h2>Payments</h2>
            <p>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
            <p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
            <p>The payment processors we work with are:</p>
            <ul>
                <li><h4>Stripe</h4>
                    <p>Their Privacy Policy can be viewed at <a href="https://stripe.com/us/privacy">https://stripe.com/us/privacy</a></p>
                </li>

                <li><h4>Przelewy24</h4>
                    <p>Their Privacy Policy can be viewed at <a href="https://www.przelewy24.pl/en/information-obligation-gdpr-payer">https://www.przelewy24.pl/en/information-obligation-gdpr-payer</a></p>
                </li>
            </ul>

            <h2>Links to Other Sites</h2>
            <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

            <h2>Children's Privacy</h2>
            <p>Our Service does not address anyone under the age of 18 ("Children").</p>
            <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

            <h2 id="cookies">Cookies</h2>
            <p>The Service uses cookies and similar files or technologies to automatically collect and store information about your computer, device, and Service usage, in order to improve their performance and enhance your user experience. We use the general term "cookies" in this policy to refer to these technologies and all such similar technologies that collect information automatically when you are using our Service where this policy is posted. </p>
            <p>If you do not accept the use of these cookies, please disable them using 'Cookies' button in footer of the Service, or by changing your browser settings so that cookies from this Service cannot be placed on your computer or mobile device. Important: disabling cookies may impair certain Service features.</p>
            <p>There are two broad categories of cookies:</p>
            <ul>
                <li><b>First party cookies</b>, served directly by us to your computer or mobile device.</li>
                <li><b>Third party cookies</b>, which are served by a third party on our behalf. We use third-party cookies for functionality, performance/analytics, marketing, unclassified and other technologies, and social media purposes. The third-party cookies are outside of our control. The third parties may, at any time, change their terms of service, purpose and use of cookies, etc.</li>
            </ul>
            <p>Cookies can remain on your computer or mobile device for different periods of time. Some cookies are 'session cookies', meaning that they exist only while your browser is open. These are deleted automatically once you close your browser. Other cookies are 'permanent cookies', meaning that they survive after your browser is closed. They can be used by websites to recognize your computer when you open your browser and browse the Internet again.</p>

            <h3>Web beacons</h3>
            <p>Cookies are not the only way to recognize or track visitors to a website. We may use other, similar technologies from time to time, like web beacons (sometimes called "tracking pixels" or "clear gifs"). These are small graphics files that contain a unique identifier that enable us to recognize when someone has visited our website. This allows us, for example, to monitor the traffic patterns of users from one page within our website to another, to deliver or communicate with cookies, to understand whether you have come to our website from an online advertisement displayed on a third-party website, to improve website performance and to measure the success of email marketing campaigns. In most instances, these technologies are reliant on cookies to function, and therefore declining cookies prevents them from functioning.</p>
            <p>You may have the right to decide whether to accept or reject cookies. When you access our Service, you are presented with a cookie consent mechanism that allows you to accept or reject cookies that are not essential cookies. Your consent is valid for 12 moths, but you can change your cookies preferences any time by clicking 'Cookie' button in the footer of the Service. You may also control cookies by setting your browser to turn off cookies. If you turn off cookies in your browser settings, web beacon and other technologies will still detect your visits to the Service; however, they will not be associated with information otherwise stored in cookies.</p>

            <h3>Targeted advertising</h3>
            <p>Third parties may drop cookies on your computer or mobile device to serve advertising through our website. These companies may use information about your visits to this and other websites in order to provide relevant advertisements about goods and services that you may be interested in. They may also employ technology that is used to measure the effectiveness of advertisements. The information collected through this process does not enable us or them to identify your name, contact details or other personally identifying details unless you choose to provide these to us.</p>

            <h3>How do we use cookies?</h3>
            <p>We use cookies to:</p>
            <ul>
                <li>track traffic flow and patterns of travel in connection with the Service;</li>
                <li>understand the total number of visitors to the Service on an ongoing basis and the types of internet browsers (e.g. Chrome, Firefox, Safari, or Internet Explorer) and operating systems (e.g. Windows or Mac) used by our visitors;</li>
                <li>monitor the performance of the Service and to continually improve it; and</li>
                <li>customize and enhance your online experience.</li>
            </ul>

            <h3>What types of cookies do we use?</h3>
            <p>The types of cookies used by us in connection with the Service can be considered 'essential website cookies', 'preferences cookies' and 'marketing cookies'.</p>
            <ul>
                <li><h4>Essential cookies</h4>
                    <p>These cookies are essential to provide you with services available through this Site and to use some of its features, such as access to secure areas. Without these cookies we will not be able to provide services that you require, such as transactional pages and secure login accounts.</p>
                </li>

                <li><h4>Preferences cookies</h4>
                    <p>These cookies record information about choices you've made and allow us to tailor the website to you. These cookies allow us to provide you with our services in the way in which you have required, as you continue to use or come back to our Site. For example, these cookies allow us to:</p>
                    <ul>
                        <li>Save your location preference if you have set your location on the homepage in order to receive a localized information;</li>
                        <li>Remember settings you have applied, such as layout, text size, preferences, and colors;</li>
                        <li>Show you when you are logged in; and</li>
                        <li>Store accessibility options.</li>
                    </ul>
                </li>

                <li><h4>Analytics Cookies</h4>
                    <p>We use performance/analytics cookies to analyze how the website is accessed, used, or is performing. We do this in order to provide you with a better user experience and to maintain, operate and continually improve the website. For example, these cookies allow us to:</p>
                    <ul>
                        <li>Better understand our website visitors so that we can improve how we present our content;</li>
                        <li>Test different design ideas for particular pages, such as our homepage;</li>
                        <li>Collect information about Site visitors such as where they are located and what browsers they are using;</li>
                        <li>Determine the number of unique users of the website;</li>
                        <li>Improve the website by measuring any errors that occur; and</li>
                        <li>Conduct research and diagnostics to improve product offerings.</li>
                    </ul>
                </li>
                <li><h4>Marketing</h4>
                    <p>We use marketing cookies to deliver many types of targeted digital marketing. We do this in order to provide you with a better user experience and to maintain, operate and continually improve the website. The cookie store user data and behavior information, which allows advertising services to target audience according to variables. For example, these cookies allow us to:</p>
                    <ul>
                        <li>Observe the site performance and generate retargeting (Site retargeting, search retargeting, etc).</li>
                        <li>Maintain and improve the website and our products</li>
                    </ul>
                </li>
            </ul>

            <h3>Third Party Websites' Cookies</h3>
            <p>When using our website, you may be directed to other websites for such activities as surveys, to make payment, or for job applications. These websites may use their own cookies. We do not have control over the placement of cookies by other websites you visit, even if you are directed to them from our website.</p>
            <p>If you use the buttons that allow you to share products and content with your friends via social networks like Google, YouTube,Twitter and Facebook, these companies may set a cookie on your computer memory. Find out more about these here:</p>
            <ul>
                <li><a href="https://www.facebook.com/about/privacy">https://www.facebook.com/about/privacy</a></li>
                <li><a href="http://twitter.com/privacy">http://twitter.com/privacy</a></li>
                <li><a href="https://www.linkedin.com/legal/privacy-policy">https://www.linkedin.com/legal/privacy-policy</a></li>
                <li><a href="http://www.google.com/intl/en-GB/policies/privacy">http://www.google.com/intl/en-GB/policies/privacy</a></li>
                <li><a href="https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement">https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement</a></li>
            </ul>

            <h2>Changes to This Privacy Policy</h2>
            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
            <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us by e-mail at <a href="mailto:legal@hdsa.pl">legal@hdsa.pl</a> </p>
        </article>
                
    </div>

    <Footer />
</div>

